### ISSUE TITLE
Ability to modify webpack config

### ISSUE THREAD

**Issue by asavage** [PolymerX/polymerx-cli#108]
I need the ability to modify how WebPack works.  My needs are two-fold:

1. Ability to have any number of environments beyond prod and dev
2. Ability to have custom environment variables that I can send to WebPack for use within the build process.

**Comment by LasaleFamine** [comment]
Hi @asavage, we should be ok with the just released v0.4.0. Refers to the [README section](https://github.com/PolymerX/polymerx-cli#webpack) for more details. Let me know if you have other problems.
