### ISSUE TITLE
Global installation with yarn no create global command polymerx

### ISSUE THREAD

**Issue by jagcolombat** [PolymerX/polymerx-cli#6]
I'm working on Windows 10 and after install polymerx-cli (yarn add global polymerx-cli), polymerx command not exist. Moving to (cd command) to node_modules/.bin into folder installation is recognized polymerx. Proccess installation should set path installation (node_modules/.bin) to system variables or explain how execute properly polymerx on Windows.

**Comment by LasaleFamine** [comment]
Hi @jagcolombat, 
actually I think your issue is related to `yarn` and the installation on your system. Did you try with NPM? 

I think your issue could be related to https://github.com/yarnpkg/yarn/issues/1491.

I'm able to work on Windows using NPM to install the `polymerx-cli` globally.

**Comment by jagcolombat** [comment]
> I'm able to work on Windows using NPM to install the polymerx-cli globally. 

Successfully confirmed

**Comment by LasaleFamine** [comment]
I'm closing this one since could be a package manager - OS related problem. 

I hope you are able to work with the CLI. Feel free to reopen this or open a new issue if you have other problems.
